name: tap_n_match
description: "A color matching puzzle game."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  intl: ^0.20.2
  google_fonts: ^8.0.2
  http: ^1.2.1
  audioplayers: ^6.1.0
  file_picker: ^8.0.0
  shared_preferences: ^2.5.5
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/audio/tap_sounds/default_tapSounds.mp3
    - assets/audio/tap_sounds/genshin_tap_sound.mp3
    - assets/audio/tap_sounds/minecraft_tap_sound.mp3
    - assets/audio/tap_sounds/snowfall_tap_sound.mp3
    - assets/audio/tap_sounds/harvest_moon_tapSound.mp3
    - assets/audio/background_music/stal_default.mp3
    - assets/audio/background_music/genshin_bgMusic.mp3
    - assets/audio/background_music/harvestMoon.mp3
    - assets/audio/background_music/minecraft_bgMusic.mp3
    - assets/audio/background_music/snowfall_bgMusic.mp3
    - assets/audio/game_over_sound/
    - assets/countdown_sound/
    - assets/background/minecraft_bgColor.jpg
    - assets/background/harvest_moon_background.jpeg
    - assets/background/genshin_background.jpeg
    - assets/background/snowfall_background.jpeg
