// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9HGQ9o4aW-fNtofQPKSZu2mE_Q3UH9eA',
    appId: '1:668061607763:web:2f097c3818b8933423a3a6',
    messagingSenderId: '668061607763',
    projectId: 'tap-and-match-98f4a',
    authDomain: 'tap-and-match-98f4a.firebaseapp.com',
    storageBucket: 'tap-and-match-98f4a.firebasestorage.app',
    measurementId: 'G-X5SVLLRXPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQliX5f5V9hDyW2Mw0DrNxdh2MRcTae8E',
    appId: '1:668061607763:android:59cdb7cc6682c5e723a3a6',
    messagingSenderId: '668061607763',
    projectId: 'tap-and-match-98f4a',
    storageBucket: 'tap-and-match-98f4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUCTVrMU0I2-lhbHQLl6sdR7TtvgpV8EE',
    appId: '1:668061607763:ios:087c7631333b0b6923a3a6',
    messagingSenderId: '668061607763',
    projectId: 'tap-and-match-98f4a',
    storageBucket: 'tap-and-match-98f4a.firebasestorage.app',
    iosBundleId: 'com.example.tapNMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUCTVrMU0I2-lhbHQLl6sdR7TtvgpV8EE',
    appId: '1:668061607763:ios:087c7631333b0b6923a3a6',
    messagingSenderId: '668061607763',
    projectId: 'tap-and-match-98f4a',
    storageBucket: 'tap-and-match-98f4a.firebasestorage.app',
    iosBundleId: 'com.example.tapNMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9HGQ9o4aW-fNtofQPKSZu2mE_Q3UH9eA',
    appId: '1:668061607763:web:f2fd36b07ac6d40823a3a6',
    messagingSenderId: '668061607763',
    projectId: 'tap-and-match-98f4a',
    authDomain: 'tap-and-match-98f4a.firebaseapp.com',
    storageBucket: 'tap-and-match-98f4a.firebasestorage.app',
    measurementId: 'G-3BBSEWHVZT',
  );
}
